"""
HTML email digest formatting and sending via SMTP.
"""

import logging
import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import config

logger = logging.getLogger(__name__)


def _event_row(event: dict) -> str:
    score = event.get("weighted_score", 0)
    return f"""
    <tr>
      <td style="padding:10px;border-bottom:1px solid #e0e0e0;">
        <strong style="font-size:15px;">{event.get('name', 'Unknown Event')}</strong><br>
        <span style="color:#555;">📅 {event.get('date', 'TBC')} &nbsp;|&nbsp; 📍 {event.get('venue', 'TBC')}</span><br>
        <span style="color:#555;">🏢 {event.get('organiser', 'Unknown')}</span><br>
        <p style="margin:6px 0;">{event.get('relevance_summary', '')}</p>
        {f'<a href="{event["url"]}" style="color:#1a73e8;">Registration / Info →</a>' if event.get('url') else ''}
      </td>
      <td style="padding:10px;border-bottom:1px solid #e0e0e0;text-align:center;vertical-align:top;">
        <span style="font-size:22px;font-weight:bold;color:{'#1b7a1b' if score >= 7 else '#b36b00' if score >= 5 else '#888'};">{score}</span><br>
        <span style="font-size:11px;color:#888;">/10</span>
      </td>
    </tr>"""


def build_html(
    high_events: list[dict],
    radar_events: list[dict],
    total_scanned: int,
    duplicates: int,
) -> str:
    today = date.today().strftime("%A %d %B %Y")

    high_rows = "\n".join(_event_row(e) for e in high_events) if high_events else """
    <tr><td colspan="2" style="padding:20px;color:#888;text-align:center;">No high-relevance events found today.</td></tr>"""

    radar_rows = "\n".join(_event_row(e) for e in radar_events) if radar_events else """
    <tr><td colspan="2" style="padding:20px;color:#888;text-align:center;">Nothing on the radar today.</td></tr>"""

    filtered_out = total_scanned - len(high_events) - len(radar_events)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,Helvetica,sans-serif;max-width:700px;margin:auto;padding:20px;color:#222;">
  <h1 style="color:#1a2e4a;border-bottom:3px solid #1a2e4a;padding-bottom:8px;">
    Defence Events Digest
  </h1>
  <p style="color:#555;">{today}</p>

  <h2 style="color:#1a2e4a;">🎯 High-Relevance Events (score ≥ {config.HIGH_RELEVANCE_MIN_SCORE})</h2>
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="text-align:left;padding:8px;">Event</th>
        <th style="width:60px;padding:8px;">Score</th>
      </tr>
    </thead>
    <tbody>{high_rows}</tbody>
  </table>

  <h2 style="color:#6b6b6b;margin-top:30px;">📡 On the Radar (score {config.RADAR_MIN_SCORE}–{config.HIGH_RELEVANCE_MIN_SCORE - 1})</h2>
  <table style="width:100%;border-collapse:collapse;">
    <thead>
      <tr style="background:#f5f5f5;">
        <th style="text-align:left;padding:8px;">Event</th>
        <th style="width:60px;padding:8px;">Score</th>
      </tr>
    </thead>
    <tbody>{radar_rows}</tbody>
  </table>

  <hr style="margin-top:30px;border:none;border-top:1px solid #ddd;">
  <p style="font-size:12px;color:#999;">
    Scanned {total_scanned} events · {duplicates} duplicates removed · {filtered_out} below threshold · Generated by Defence Events Tracker
  </p>
</body>
</html>"""


def send_digest(
    high_events: list[dict],
    radar_events: list[dict],
    total_scanned: int,
    duplicates: int,
) -> bool:
    recipient = os.getenv("RECIPIENT_EMAIL")
    if not recipient:
        logger.error("RECIPIENT_EMAIL not set – skipping email send")
        return False

    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")

    html = build_html(high_events, radar_events, total_scanned, duplicates)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = config.EMAIL_SUBJECT
    msg["From"] = smtp_user
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [recipient], msg.as_string())
        logger.info("Digest email sent to %s", recipient)
        return True
    except Exception as exc:
        logger.error("Failed to send email: %s", exc)
        return False
