"""
HTML email digest formatting and SMTP sending.
"""

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

import config

logger = logging.getLogger(__name__)


def _event_row(event: dict) -> str:
    name = event.get("name", "Unknown Event")
    date = event.get("date", "TBC")
    venue = event.get("venue") or "Venue TBC"
    url = event.get("url") or "#"
    score = event.get("relevance_score", 0)
    summary = event.get("relevance_summary", "")

    link_html = f'<a href="{url}">Register / Info</a>' if url and url != "#" else "No link available"

    return f"""
    <tr>
      <td style="padding:12px; border-bottom:1px solid #e0e0e0;">
        <strong style="font-size:15px;">{name}</strong><br>
        <span style="color:#555;">📅 {date} &nbsp;|&nbsp; 📍 {venue}</span><br>
        <span style="color:#333; font-size:13px;">{summary}</span><br>
        <span style="margin-top:4px; display:inline-block;">{link_html}</span>
      </td>
      <td style="padding:12px; border-bottom:1px solid #e0e0e0; text-align:center;
                 font-size:20px; font-weight:bold; color:#1a5276;">
        {score}
      </td>
    </tr>"""


def build_html(
    headline_events: list[dict],
    radar_events: list[dict],
    total_scanned: int,
    total_filtered: int,
) -> str:
    today = datetime.now().strftime("%A %d %B %Y")

    headline_rows = "".join(_event_row(e) for e in headline_events)
    radar_rows = "".join(_event_row(e) for e in radar_events)

    headline_section = ""
    if headline_events:
        headline_section = f"""
        <h2 style="color:#1a5276; border-bottom:2px solid #1a5276; padding-bottom:6px;">
          Top Events (score &ge; {config.MIN_SCORE_HEADLINE}/10)
        </h2>
        <table style="width:100%; border-collapse:collapse;">
          <tr style="background:#1a5276; color:white;">
            <th style="padding:10px; text-align:left;">Event</th>
            <th style="padding:10px; width:60px;">Score</th>
          </tr>
          {headline_rows}
        </table>"""
    else:
        headline_section = "<p>No high-scoring events found today.</p>"

    radar_section = ""
    if radar_events:
        radar_section = f"""
        <h2 style="color:#6c757d; border-bottom:2px solid #6c757d; padding-bottom:6px; margin-top:30px;">
          On the Radar (score {config.MIN_SCORE_ON_RADAR}&ndash;{config.MIN_SCORE_HEADLINE - 1}/10)
        </h2>
        <table style="width:100%; border-collapse:collapse;">
          <tr style="background:#6c757d; color:white;">
            <th style="padding:10px; text-align:left;">Event</th>
            <th style="padding:10px; width:60px;">Score</th>
          </tr>
          {radar_rows}
        </table>"""

    return f"""
    <html>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                 max-width:700px; margin:auto; padding:20px; color:#222;">
      <h1 style="color:#1a5276;">Defence Events Digest</h1>
      <p style="color:#555;">{today}</p>

      {headline_section}
      {radar_section}

      <hr style="margin-top:30px; border:none; border-top:1px solid #ccc;">
      <p style="font-size:12px; color:#888;">
        Scanned {total_scanned} events &bull; {total_filtered} filtered out
        (duplicates or below threshold) &bull; Generated by Defence Events Tracker
      </p>
    </body>
    </html>"""


def send_digest(
    headline_events: list[dict],
    radar_events: list[dict],
    total_scanned: int,
    total_filtered: int,
) -> bool:
    """Build and send the daily digest email. Returns True on success."""
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    recipient = os.getenv("RECIPIENT_EMAIL")

    if not all([smtp_host, smtp_user, smtp_pass, recipient]):
        logger.warning("SMTP not configured – skipping email send")
        return False

    html = build_html(headline_events, radar_events, total_scanned, total_filtered)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = config.EMAIL_SUBJECT
    msg["From"] = f"{config.EMAIL_FROM_NAME} <{smtp_user}>"
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [recipient], msg.as_string())
        logger.info("Digest email sent to %s", recipient)
        return True
    except Exception:
        logger.exception("Failed to send digest email")
        return False
